# Languages
#   配置网站语言
#   文档: https://docs.hugoblox.com/reference/language/

# 设置中文 (zh) 为该网站的语言
zh:
  languageCode: zh-Hans
  # 【关键修改】这里改为 content，因为您的文章都在 content 根目录下，而不是 content/zh
  contentDir: content
  title: 谢姥姥的碎碎念
  params:
    description: 这是一个关于分享的博客...
  menu:
    main:
      - name: 首页
        url: /
        weight: 10
      - name: 热门话题
        url: tags/
        weight: 20
