# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: /
    weight: 10
  - name: 热门话题
    url: tags/
    weight: 20
#  - name: Uses
#    url: uses/
#    weight: 30
